import { parseJWTClient } from '@/lib/jwt/parseJWTClient'
import { generateJWT } from '@/lib/jwt/jwt'
import { readPemEnvBase64 } from '@/lib/jwt/readPemEnvBase64'
import { beforeAll, describe, expect, test } from '@jest/globals'

function invalid(message: string) {
    return { success: false, errorCode: 'JWT INVALID', error: [{ message }] }
}

describe('parseJWTClient', () => {
    let publicKey: string
    let token: string

    beforeAll(() => {
        publicKey = readPemEnvBase64(process.env.JWT_PUBLIC_KEY ?? '')
        token = generateJWT('omegaid', { sub: 1 }, 60)
    })

    test('accepts a token generated by the server', async () => {
        await expect(parseJWTClient(token, publicKey, 0, 'omegaid')).resolves.toEqual({ success: true, data: 1 })
    })

    test('rejects a token whose signature does not match', async () => {
        const [header, payload, signature] = token.split('.')
        const tampered = Buffer.from(signature, 'base64url')
        tampered[0] = (tampered[0] + 1) % 256

        await expect(
            parseJWTClient(`${header}.${payload}.${tampered.toString('base64url')}`, publicKey, 0, 'omegaid')
        ).resolves.toMatchObject(invalid('Invalid JWT signature'))
    })

    test('returns an error rather than throwing for a signature that is not base64', async () => {
        const [header, payload] = token.split('.')

        await expect(
            parseJWTClient(`${header}.${payload}.!`, publicKey, 0, 'omegaid')
        ).resolves.toMatchObject(invalid('Malformatted JWT'))
    })

    test('returns an error rather than throwing for a public key that cannot be imported', async () => {
        await expect(parseJWTClient(token, 'not a key', 0, 'omegaid')).resolves.toMatchObject(invalid('Malformatted JWT'))
    })

    test('rejects a token for another audience', async () => {
        await expect(
            parseJWTClient(token, publicKey, 0, 'resetpassword')
        ).resolves.toMatchObject(invalid('Invalid audience'))
    })
})
